<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="9" hostname="QIN5CD04618ZL" failures="44" tests="59" name="Player Controller Tests" time="43.335" errors="0" timestamp="2025-08-10T20:08:29 TRT">
  <testcase classname="api.PlayerDeleteTest" name="@BeforeMethod setUp" time="0.085">
    <failure type="java.lang.AssertionError" message="Expected HTTP status code 200, but was 400 expected [200] but found [400]">
      <![CDATA[java.lang.AssertionError: Expected HTTP status code 200, but was 400 expected [200] but found [400]
at api.client.ResponseWrapper.expectingStatusCode(ResponseWrapper.java:49)
at api.PlayerDeleteTest.createAndVerifyPlayer(PlayerDeleteTest.java:185)
at api.PlayerDeleteTest.setUp(PlayerDeleteTest.java:38)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeMethod setUp -->
  <testcase classname="api.PlayerDeleteTest" name="@AfterMethod tearDown" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase classname="api.PlayerDeleteTest" name="@BeforeMethod setUp" time="0.0">
    <skipped/>
  </testcase> <!-- @BeforeMethod setUp -->
  <testcase classname="api.PlayerDeleteTest" name="@AfterMethod tearDown" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase classname="api.PlayerDeleteTest" name="@BeforeMethod setUp" time="0.0">
    <skipped/>
  </testcase> <!-- @BeforeMethod setUp -->
  <testcase classname="api.PlayerDeleteTest" name="@AfterMethod tearDown" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase classname="api.PlayerDeleteTest" name="@BeforeMethod setUp" time="0.0">
    <skipped/>
  </testcase> <!-- @BeforeMethod setUp -->
  <testcase classname="api.PlayerDeleteTest" name="@AfterMethod tearDown" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase classname="api.PlayerUpdateTest" name="@BeforeMethod setUp" time="0.083">
    <failure type="java.lang.AssertionError" message="User should be created. expected [200] but found [400]">
      <![CDATA[java.lang.AssertionError: User should be created. expected [200] but found [400]
at api.PlayerUpdateTest.createAndVerifyPlayer(PlayerUpdateTest.java:258)
at api.PlayerUpdateTest.setUp(PlayerUpdateTest.java:37)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeMethod setUp -->
  <testcase classname="api.PlayerUpdateTest" name="@AfterMethod tearDown" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase classname="api.PlayerUpdateTest" name="@BeforeMethod setUp" time="0.0">
    <skipped/>
  </testcase> <!-- @BeforeMethod setUp -->
  <testcase classname="api.PlayerUpdateTest" name="@AfterMethod tearDown" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase classname="api.PlayerUpdateTest" name="@BeforeMethod setUp" time="0.096">
    <failure type="java.lang.AssertionError" message="User should be created. expected [200] but found [400]">
      <![CDATA[java.lang.AssertionError: User should be created. expected [200] but found [400]
at api.PlayerUpdateTest.createAndVerifyPlayer(PlayerUpdateTest.java:258)
at api.PlayerUpdateTest.setUp(PlayerUpdateTest.java:37)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeMethod setUp -->
  <testcase classname="api.PlayerUpdateTest" name="@AfterMethod tearDown" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase classname="api.PlayerUpdateTest" name="@AfterMethod tearDown" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase classname="api.PlayerAdminEditorTest" name="testAdminCanUpdateOtherAdmins" time="0.429">
    <failure type="java.lang.AssertionError" message="Response body is empty; cannot map to PlayerResponse">
      <![CDATA[java.lang.AssertionError: Response body is empty; cannot map to PlayerResponse
at api.client.ResponseWrapper.readEntity(ResponseWrapper.java:36)
at api.PlayerAdminEditorTest.verifyPlayerFieldUpdate(PlayerAdminEditorTest.java:112)
at api.PlayerAdminEditorTest.testAdminCanUpdateOtherAdmins(PlayerAdminEditorTest.java:77)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testAdminCanUpdateOtherAdmins -->
  <testcase classname="api.PlayerAdminEditorTest" name="testAdminCanDeleteOtherAdmins" time="0.497">
    <failure type="java.lang.AssertionError" message="Expected HTTP status code 404, but was 200 expected [404] but found [200]">
      <![CDATA[java.lang.AssertionError: Expected HTTP status code 404, but was 200 expected [404] but found [200]
at api.client.ResponseWrapper.expectingStatusCode(ResponseWrapper.java:49)
at api.PlayerAdminEditorTest.verifyPlayerDeletion(PlayerAdminEditorTest.java:140)
at api.PlayerAdminEditorTest.testAdminCanDeleteOtherAdmins(PlayerAdminEditorTest.java:89)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- testAdminCanDeleteOtherAdmins -->
  <testcase classname="api.PlayerControllerTest" name="testCompletePlayerLifecycle" time="5.796">
    <failure type="java.lang.AssertionError" message="Expected HTTP status code 404, but was 200 expected [404] but found [200]">
      <![CDATA[java.lang.AssertionError: Expected HTTP status code 404, but was 200 expected [404] but found [200]
at api.client.ResponseWrapper.expectingStatusCode(ResponseWrapper.java:49)
at api.PlayerControllerTest.testCompletePlayerLifecycle(PlayerControllerTest.java:113)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- testCompletePlayerLifecycle -->
  <testcase classname="api.PlayerCreateDuplicateNegativeTest" name="testCreatePlayerWithDuplicateLogin" time="0.106">
    <failure type="java.lang.AssertionError" message="Expected HTTP status code 403, but was 200 expected [403] but found [200]">
      <![CDATA[java.lang.AssertionError: Expected HTTP status code 403, but was 200 expected [403] but found [200]
at api.client.ResponseWrapper.expectingStatusCode(ResponseWrapper.java:49)
at api.PlayerCreateDuplicateNegativeTest.assertCreatePlayerWithValidationError(PlayerCreateDuplicateNegativeTest.java:92)
at api.PlayerCreateDuplicateNegativeTest.testCreatePlayerWithDuplicateLogin(PlayerCreateDuplicateNegativeTest.java:61)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- testCreatePlayerWithDuplicateLogin -->
  <testcase classname="api.PlayerCreateDuplicateNegativeTest" name="testCreatePlayerWithDuplicateScreenName" time="0.112">
    <failure type="java.lang.AssertionError" message="Expected HTTP status code 403, but was 200 expected [403] but found [200]">
      <![CDATA[java.lang.AssertionError: Expected HTTP status code 403, but was 200 expected [403] but found [200]
at api.client.ResponseWrapper.expectingStatusCode(ResponseWrapper.java:49)
at api.PlayerCreateDuplicateNegativeTest.assertCreatePlayerWithValidationError(PlayerCreateDuplicateNegativeTest.java:92)
at api.PlayerCreateDuplicateNegativeTest.testCreatePlayerWithDuplicateScreenName(PlayerCreateDuplicateNegativeTest.java:69)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- testCreatePlayerWithDuplicateScreenName -->
  <testcase classname="api.PlayerCreateTest" name="testCreatePlayerWithAdminRole" time="0.112"/>
  <testcase classname="api.PlayerCreateTest" name="testCreatePlayerWithInvalidAgeTooOld" time="0.098">
    <failure type="java.lang.AssertionError" message="Response body is empty; cannot map to ErrorBody">
      <![CDATA[java.lang.AssertionError: Response body is empty; cannot map to ErrorBody
at api.client.ResponseWrapper.readError(ResponseWrapper.java:56)
at api.PlayerCreateTest.assertCreatePlayerWithValidationError(PlayerCreateTest.java:272)
at api.PlayerCreateTest.testCreatePlayerWithInvalidAgeTooOld(PlayerCreateTest.java:125)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testCreatePlayerWithInvalidAgeTooOld -->
  <testcase classname="api.PlayerCreateTest" name="testCreatePlayerWithInvalidAgeTooYoung" time="0.089">
    <failure type="java.lang.AssertionError" message="Response body is empty; cannot map to ErrorBody">
      <![CDATA[java.lang.AssertionError: Response body is empty; cannot map to ErrorBody
at api.client.ResponseWrapper.readError(ResponseWrapper.java:56)
at api.PlayerCreateTest.assertCreatePlayerWithValidationError(PlayerCreateTest.java:272)
at api.PlayerCreateTest.testCreatePlayerWithInvalidAgeTooYoung(PlayerCreateTest.java:115)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testCreatePlayerWithInvalidAgeTooYoung -->
  <testcase classname="api.PlayerCreateTest" name="testCreatePlayerWithInvalidGender" time="0.091">
    <failure type="java.lang.AssertionError" message="User should not be created. expected [400] but found [200]">
      <![CDATA[java.lang.AssertionError: User should not be created. expected [400] but found [200]
at api.PlayerCreateTest.assertCreatePlayerWithValidationError(PlayerCreateTest.java:271)
at api.PlayerCreateTest.testCreatePlayerWithInvalidGender(PlayerCreateTest.java:137)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- testCreatePlayerWithInvalidGender -->
  <testcase classname="api.PlayerCreateTest" name="testCreatePlayerWithInvalidPasswordNoLetters" time="0.094">
    <failure type="java.lang.AssertionError" message="User should not be created. expected [400] but found [200]">
      <![CDATA[java.lang.AssertionError: User should not be created. expected [400] but found [200]
at api.PlayerCreateTest.assertCreatePlayerWithValidationError(PlayerCreateTest.java:271)
at api.PlayerCreateTest.testCreatePlayerWithInvalidPasswordNoLetters(PlayerCreateTest.java:179)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- testCreatePlayerWithInvalidPasswordNoLetters -->
  <testcase classname="api.PlayerCreateTest" name="testCreatePlayerWithInvalidPasswordNoNumbers" time="0.089">
    <failure type="java.lang.AssertionError" message="User should not be created. expected [400] but found [200]">
      <![CDATA[java.lang.AssertionError: User should not be created. expected [400] but found [200]
at api.PlayerCreateTest.assertCreatePlayerWithValidationError(PlayerCreateTest.java:271)
at api.PlayerCreateTest.testCreatePlayerWithInvalidPasswordNoNumbers(PlayerCreateTest.java:169)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- testCreatePlayerWithInvalidPasswordNoNumbers -->
  <testcase classname="api.PlayerCreateTest" name="testCreatePlayerWithInvalidPasswordTooLong" time="0.086">
    <failure type="java.lang.AssertionError" message="User should not be created. expected [400] but found [200]">
      <![CDATA[java.lang.AssertionError: User should not be created. expected [400] but found [200]
at api.PlayerCreateTest.assertCreatePlayerWithValidationError(PlayerCreateTest.java:271)
at api.PlayerCreateTest.testCreatePlayerWithInvalidPasswordTooLong(PlayerCreateTest.java:159)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- testCreatePlayerWithInvalidPasswordTooLong -->
  <testcase classname="api.PlayerCreateTest" name="testCreatePlayerWithInvalidPasswordTooShort" time="0.086">
    <failure type="java.lang.AssertionError" message="User should not be created. expected [400] but found [200]">
      <![CDATA[java.lang.AssertionError: User should not be created. expected [400] but found [200]
at api.PlayerCreateTest.assertCreatePlayerWithValidationError(PlayerCreateTest.java:271)
at api.PlayerCreateTest.testCreatePlayerWithInvalidPasswordTooShort(PlayerCreateTest.java:149)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- testCreatePlayerWithInvalidPasswordTooShort -->
  <testcase classname="api.PlayerCreateTest" name="testCreatePlayerWithInvalidRole" time="0.082">
    <failure type="java.lang.AssertionError" message="Response body is empty; cannot map to ErrorBody">
      <![CDATA[java.lang.AssertionError: Response body is empty; cannot map to ErrorBody
at api.client.ResponseWrapper.readError(ResponseWrapper.java:56)
at api.PlayerCreateTest.assertCreatePlayerWithValidationError(PlayerCreateTest.java:272)
at api.PlayerCreateTest.testCreatePlayerWithInvalidRole(PlayerCreateTest.java:190)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testCreatePlayerWithInvalidRole -->
  <testcase classname="api.PlayerCreateTest" name="testCreatePlayerWithMissingAge" time="0.091">
    <failure type="java.lang.AssertionError" message="Response body is empty; cannot map to ErrorBody">
      <![CDATA[java.lang.AssertionError: Response body is empty; cannot map to ErrorBody
at api.client.ResponseWrapper.readError(ResponseWrapper.java:56)
at api.PlayerCreateTest.assertCreatePlayerWithValidationError(PlayerCreateTest.java:272)
at api.PlayerCreateTest.testCreatePlayerWithMissingAge(PlayerCreateTest.java:201)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testCreatePlayerWithMissingAge -->
  <testcase classname="api.PlayerCreateTest" name="testCreatePlayerWithMissingGender" time="0.094">
    <failure type="java.lang.AssertionError" message="Response body is empty; cannot map to ErrorBody">
      <![CDATA[java.lang.AssertionError: Response body is empty; cannot map to ErrorBody
at api.client.ResponseWrapper.readError(ResponseWrapper.java:56)
at api.PlayerCreateTest.assertCreatePlayerWithValidationError(PlayerCreateTest.java:272)
at api.PlayerCreateTest.testCreatePlayerWithMissingGender(PlayerCreateTest.java:210)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testCreatePlayerWithMissingGender -->
  <testcase classname="api.PlayerCreateTest" name="testCreatePlayerWithMissingLogin" time="0.098">
    <failure type="java.lang.AssertionError" message="Response body is empty; cannot map to ErrorBody">
      <![CDATA[java.lang.AssertionError: Response body is empty; cannot map to ErrorBody
at api.client.ResponseWrapper.readError(ResponseWrapper.java:56)
at api.PlayerCreateTest.assertCreatePlayerWithValidationError(PlayerCreateTest.java:272)
at api.PlayerCreateTest.testCreatePlayerWithMissingLogin(PlayerCreateTest.java:219)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testCreatePlayerWithMissingLogin -->
  <testcase classname="api.PlayerCreateTest" name="testCreatePlayerWithMissingRole" time="0.11">
    <failure type="java.lang.AssertionError" message="Response body is empty; cannot map to ErrorBody">
      <![CDATA[java.lang.AssertionError: Response body is empty; cannot map to ErrorBody
at api.client.ResponseWrapper.readError(ResponseWrapper.java:56)
at api.PlayerCreateTest.assertCreatePlayerWithValidationError(PlayerCreateTest.java:272)
at api.PlayerCreateTest.testCreatePlayerWithMissingRole(PlayerCreateTest.java:228)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testCreatePlayerWithMissingRole -->
  <testcase classname="api.PlayerCreateTest" name="testCreatePlayerWithMissingScreenName" time="0.095">
    <failure type="java.lang.AssertionError" message="Response body is empty; cannot map to ErrorBody">
      <![CDATA[java.lang.AssertionError: Response body is empty; cannot map to ErrorBody
at api.client.ResponseWrapper.readError(ResponseWrapper.java:56)
at api.PlayerCreateTest.assertCreatePlayerWithValidationError(PlayerCreateTest.java:272)
at api.PlayerCreateTest.testCreatePlayerWithMissingScreenName(PlayerCreateTest.java:237)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testCreatePlayerWithMissingScreenName -->
  <testcase classname="api.PlayerCreateTest" name="testCreatePlayerWithNonExistentEditor" time="0.092">
    <failure type="java.lang.AssertionError" message="Response body is empty; cannot map to ErrorBody">
      <![CDATA[java.lang.AssertionError: Response body is empty; cannot map to ErrorBody
at api.client.ResponseWrapper.readError(ResponseWrapper.java:56)
at api.PlayerCreateTest.assertCreatePlayerWithAuthorizationError(PlayerCreateTest.java:282)
at api.PlayerCreateTest.testCreatePlayerWithNonExistentEditor(PlayerCreateTest.java:248)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testCreatePlayerWithNonExistentEditor -->
  <testcase classname="api.PlayerCreateTest" name="testCreatePlayerWithUserRole" time="0.092"/>
  <testcase classname="api.PlayerCreateTest" name="testCreatePlayerWithValidDataUsingAdmin" time="0.103">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Wrong age expected [53] but found [null],
	Wrong gender expected [female] but found [null],
	Wrong password expected [TX2V6JVe084J3b] but found [null],
	Wrong role expected [user] but found [null],
	Wrong screen_name expected [04a0c6d8] but found [null]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Wrong age expected [53] but found [null],
Wrong gender expected [female] but found [null],
Wrong password expected [TX2V6JVe084J3b] but found [null],
Wrong role expected [user] but found [null],
Wrong screen_name expected [04a0c6d8] but found [null]
at api.PlayerCreateTest.assertPlayerEquals(PlayerCreateTest.java:296)
at api.PlayerCreateTest.testCreatePlayerWithValidDataUsingAdmin(PlayerCreateTest.java:74)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- testCreatePlayerWithValidDataUsingAdmin -->
  <testcase classname="api.PlayerCreateTest" name="testCreatePlayerWithValidDataUsingSupervisor" time="0.087">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Wrong age expected [49] but found [null],
	Wrong gender expected [female] but found [null],
	Wrong password expected [YWN5mPg2diT3mOc] but found [null],
	Wrong role expected [user] but found [null],
	Wrong screen_name expected [987ac94d] but found [null]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Wrong age expected [49] but found [null],
Wrong gender expected [female] but found [null],
Wrong password expected [YWN5mPg2diT3mOc] but found [null],
Wrong role expected [user] but found [null],
Wrong screen_name expected [987ac94d] but found [null]
at api.PlayerCreateTest.assertPlayerEquals(PlayerCreateTest.java:296)
at api.PlayerCreateTest.testCreatePlayerWithValidDataUsingSupervisor(PlayerCreateTest.java:61)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- testCreatePlayerWithValidDataUsingSupervisor -->
  <testcase classname="api.PlayerCreateWithAdminEditorNegativeTest" name="testAdminCannotCreateSupervisor" time="0.098">
    <failure type="java.lang.AssertionError" message="Expected HTTP status code 403, but was 400 expected [403] but found [400]">
      <![CDATA[java.lang.AssertionError: Expected HTTP status code 403, but was 400 expected [403] but found [400]
at api.client.ResponseWrapper.expectingStatusCode(ResponseWrapper.java:49)
at api.PlayerCreateWithAdminEditorNegativeTest.assertCreatePlayerWithAuthorizationError(PlayerCreateWithAdminEditorNegativeTest.java:89)
at api.PlayerCreateWithAdminEditorNegativeTest.testAdminCannotCreateSupervisor(PlayerCreateWithAdminEditorNegativeTest.java:62)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- testAdminCannotCreateSupervisor -->
  <testcase classname="api.PlayerCreateWithUserEditorNegativeTest" name="testCreatePlayerWithUserEditor" time="0.093">
    <failure type="java.lang.AssertionError" message="Response body is empty; cannot map to ErrorBody">
      <![CDATA[java.lang.AssertionError: Response body is empty; cannot map to ErrorBody
at api.client.ResponseWrapper.readError(ResponseWrapper.java:56)
at api.PlayerCreateWithUserEditorNegativeTest.assertCreatePlayerWithAuthorizationError(PlayerCreateWithUserEditorNegativeTest.java:96)
at api.PlayerCreateWithUserEditorNegativeTest.testCreatePlayerWithUserEditor(PlayerCreateWithUserEditorNegativeTest.java:62)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testCreatePlayerWithUserEditor -->
  <testcase classname="api.PlayerCreateWithUserEditorNegativeTest" name="testUserCannotAccessAdminOperations" time="0.09">
    <failure type="java.lang.AssertionError" message="Response body is empty; cannot map to ErrorBody">
      <![CDATA[java.lang.AssertionError: Response body is empty; cannot map to ErrorBody
at api.client.ResponseWrapper.readError(ResponseWrapper.java:56)
at api.PlayerCreateWithUserEditorNegativeTest.assertCreatePlayerWithAuthorizationError(PlayerCreateWithUserEditorNegativeTest.java:96)
at api.PlayerCreateWithUserEditorNegativeTest.testUserCannotAccessAdminOperations(PlayerCreateWithUserEditorNegativeTest.java:72)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testUserCannotAccessAdminOperations -->
  <testcase classname="api.PlayerDeleteTest" name="testAdminCanDeleteOtherUsers" time="0.178">
    <failure type="java.lang.AssertionError" message="Expected status code 404 for not found user. expected [404] but found [200]">
      <![CDATA[java.lang.AssertionError: Expected status code 404 for not found user. expected [404] but found [200]
at api.PlayerDeleteTest.verifyPlayerDeletion(PlayerDeleteTest.java:201)
at api.PlayerDeleteTest.testAdminCanDeleteOtherUsers(PlayerDeleteTest.java:161)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- testAdminCanDeleteOtherUsers -->
  <testcase classname="api.PlayerDeleteTest" name="testDeleteAdminByAdmin" time="0.096">
    <failure type="java.lang.AssertionError" message="Status code should be 403 when admin tries to delete himself expected [403] but found [204]">
      <![CDATA[java.lang.AssertionError: Status code should be 403 when admin tries to delete himself expected [403] but found [204]
at api.PlayerDeleteTest.testDeleteAdminByAdmin(PlayerDeleteTest.java:130)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteAdminByAdmin -->
  <testcase classname="api.PlayerDeleteTest" name="testDeleteAdminBySupervisor" time="0.165">
    <failure type="java.lang.AssertionError" message="Expected status code 404 for not found user. expected [404] but found [200]">
      <![CDATA[java.lang.AssertionError: Expected status code 404 for not found user. expected [404] but found [200]
at api.PlayerDeleteTest.verifyPlayerDeletion(PlayerDeleteTest.java:201)
at api.PlayerDeleteTest.testDeleteAdminBySupervisor(PlayerDeleteTest.java:95)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteAdminBySupervisor -->
  <testcase classname="api.PlayerDeleteTest" name="testDeleteNonExistentPlayer" time="0.091">
    <failure type="java.lang.AssertionError" message="Status code should be 404 when deleting non-existent player expected [404] but found [403]">
      <![CDATA[java.lang.AssertionError: Status code should be 404 when deleting non-existent player expected [404] but found [403]
at api.PlayerDeleteTest.testDeleteNonExistentPlayer(PlayerDeleteTest.java:104)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteNonExistentPlayer -->
  <testcase classname="api.PlayerDeleteTest" name="testDeletePlayerWithAdmin" time="0.169">
    <failure type="java.lang.AssertionError" message="Expected status code 404 for not found user. expected [404] but found [200]">
      <![CDATA[java.lang.AssertionError: Expected status code 404 for not found user. expected [404] but found [200]
at api.PlayerDeleteTest.verifyPlayerDeletion(PlayerDeleteTest.java:201)
at api.PlayerDeleteTest.testDeletePlayerWithAdmin(PlayerDeleteTest.java:83)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- testDeletePlayerWithAdmin -->
  <testcase classname="api.PlayerDeleteTest" name="testDeletePlayerWithBoundaryIds" time="0.087">
    <failure type="java.lang.AssertionError" message="Status code should be 404 when deleting player with very large ID expected [400] but found [403]">
      <![CDATA[java.lang.AssertionError: Status code should be 404 when deleting player with very large ID expected [400] but found [403]
at api.PlayerDeleteTest.testDeletePlayerWithBoundaryIds(PlayerDeleteTest.java:171)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- testDeletePlayerWithBoundaryIds -->
  <testcase classname="api.PlayerDeleteTest" name="testDeletePlayerWithNonExistentEditor" time="0.116">
    <failure type="java.lang.AssertionError" message="Status code should be 403 when deleting with non-existent editor expected [403] but found [204]">
      <![CDATA[java.lang.AssertionError: Status code should be 403 when deleting with non-existent editor expected [403] but found [204]
at api.PlayerDeleteTest.testDeletePlayerWithNonExistentEditor(PlayerDeleteTest.java:112)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- testDeletePlayerWithNonExistentEditor -->
  <testcase classname="api.PlayerDeleteTest" name="testDeletePlayerWithSupervisor" time="0.0">
    <skipped/>
  </testcase> <!-- testDeletePlayerWithSupervisor -->
  <testcase classname="api.PlayerDeleteTest" name="testDeleteSupervisor" time="0.0">
    <skipped/>
  </testcase> <!-- testDeleteSupervisor -->
  <testcase classname="api.PlayerDeleteTest" name="testDeleteUserByUser" time="0.0">
    <skipped/>
  </testcase> <!-- testDeleteUserByUser -->
  <testcase classname="api.PlayerDeleteTest" name="testUserCannotDeleteAdmin" time="0.0">
    <skipped/>
  </testcase> <!-- testUserCannotDeleteAdmin -->
  <testcase classname="api.PlayerControllerTest" name="testDataConsistencyWorkflow" time="10.988"/>
  <testcase classname="api.PlayerControllerTest" name="testMultiUserWorkflow" time="10.671">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Users should have different screen names did not expect [null] but found [null]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Users should have different screen names did not expect [null] but found [null]
at api.PlayerControllerTest.testMultiUserWorkflow(PlayerControllerTest.java:168)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- testMultiUserWorkflow -->
  <testcase classname="api.PlayerGetTest" name="testGetPlayerAfterCreation" time="0.096">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Age should match expected [47] but found [24],
	Gender should match expected [female] but found [male],
	Login should match expected [dana.pfannerstill] but found [gail.wehner],
	Password should match expected [6591ee1FpI2N8W9] but found [SZi1lC78ywAeMi],
	ScreenName should match expected [c87c109c] but found [91ad93a9]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Age should match expected [47] but found [24],
Gender should match expected [female] but found [male],
Login should match expected [dana.pfannerstill] but found [gail.wehner],
Password should match expected [6591ee1FpI2N8W9] but found [SZi1lC78ywAeMi],
ScreenName should match expected [c87c109c] but found [91ad93a9]
at api.PlayerGetTest.testGetPlayerAfterCreation(PlayerGetTest.java:108)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- testGetPlayerAfterCreation -->
  <testcase classname="api.PlayerGetTest" name="testGetPlayerByNonExistentId" time="0.093">
    <failure type="java.lang.AssertionError" message="Expected HTTP status code 404, but was 200 expected [404] but found [200]">
      <![CDATA[java.lang.AssertionError: Expected HTTP status code 404, but was 200 expected [404] but found [200]
at api.client.ResponseWrapper.expectingStatusCode(ResponseWrapper.java:49)
at api.PlayerGetTest.testGetPlayerByNonExistentId(PlayerGetTest.java:76)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- testGetPlayerByNonExistentId -->
  <testcase classname="api.PlayerGetTest" name="testGetAllPlayers" time="1.6"/>
  <testcase classname="api.PlayerGetTest" name="testGetPlayerWithNullId" time="0.09">
    <failure type="java.lang.AssertionError" message="Expected HTTP status code 400, but was 200 expected [400] but found [200]">
      <![CDATA[java.lang.AssertionError: Expected HTTP status code 400, but was 200 expected [400] but found [200]
at api.client.ResponseWrapper.expectingStatusCode(ResponseWrapper.java:49)
at api.PlayerGetTest.testGetPlayerWithNullId(PlayerGetTest.java:86)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- testGetPlayerWithNullId -->
  <testcase classname="api.PlayerUpdateTest" name="testUpdateMultipleFields" time="0.1">
    <failure type="java.lang.AssertionError" message="Expected HTTP status code 200, but was 409 expected [200] but found [409]">
      <![CDATA[java.lang.AssertionError: Expected HTTP status code 200, but was 409 expected [200] but found [409]
at api.client.ResponseWrapper.expectingStatusCode(ResponseWrapper.java:49)
at api.PlayerUpdateTest.testUpdateMultipleFields(PlayerUpdateTest.java:149)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- testUpdateMultipleFields -->
  <testcase classname="api.PlayerUpdateTest" name="testUpdateNonExistentPlayer" time="0.104">
    <failure type="java.lang.AssertionError" message="Expected HTTP status code 404, but was 200 expected [404] but found [200]">
      <![CDATA[java.lang.AssertionError: Expected HTTP status code 404, but was 200 expected [404] but found [200]
at api.client.ResponseWrapper.expectingStatusCode(ResponseWrapper.java:49)
at api.PlayerUpdateTest.assertUpdatePlayerWithAuthorizationError(PlayerUpdateTest.java:311)
at api.PlayerUpdateTest.testUpdateNonExistentPlayer(PlayerUpdateTest.java:204)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- testUpdateNonExistentPlayer -->
  <testcase classname="api.PlayerGetTest" name="testGetPlayerWithBoundaryIds" time="10.166">
    <failure type="java.lang.AssertionError" message="Expected HTTP status code 400, but was 200 expected [400] but found [200]">
      <![CDATA[java.lang.AssertionError: Expected HTTP status code 400, but was 200 expected [400] but found [200]
at api.client.ResponseWrapper.expectingStatusCode(ResponseWrapper.java:49)
at api.PlayerGetTest.testGetPlayerWithBoundaryIds(PlayerGetTest.java:129)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- testGetPlayerWithBoundaryIds -->
  <testcase classname="api.PlayerUpdateTest" name="testUpdatePlayerLogin" time="0.163"/>
  <testcase classname="api.PlayerUpdateTest" name="testUpdatePlayerAge" time="10.174">
    <failure type="java.lang.AssertionError" message="Age should be updated correctly expected [30] but found [47]">
      <![CDATA[java.lang.AssertionError: Age should be updated correctly expected [30] but found [47]
at api.PlayerUpdateTest.verifyPlayerFieldUpdate(PlayerUpdateTest.java:277)
at api.PlayerUpdateTest.testUpdatePlayerAge(PlayerUpdateTest.java:71)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- testUpdatePlayerAge -->
  <testcase classname="api.PlayerUpdateTest" name="testUpdatePlayerGender" time="10.164"/>
  <testcase classname="api.PlayerUpdateTest" name="testUpdatePlayerPassword" time="10.165"/>
  <testcase classname="api.PlayerUpdateTest" name="testUpdatePlayerWithInvalidAge" time="0.087">
    <failure type="java.lang.AssertionError" message="Expected HTTP status code 403, but was 200 expected [403] but found [200]">
      <![CDATA[java.lang.AssertionError: Expected HTTP status code 403, but was 200 expected [403] but found [200]
at api.client.ResponseWrapper.expectingStatusCode(ResponseWrapper.java:49)
at api.PlayerUpdateTest.assertUpdatePlayerWithValidationError(PlayerUpdateTest.java:301)
at api.PlayerUpdateTest.testUpdatePlayerWithInvalidAge(PlayerUpdateTest.java:172)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- testUpdatePlayerWithInvalidAge -->
  <testcase classname="api.PlayerUpdateTest" name="testUpdatePlayerWithInvalidGender" time="0.082">
    <failure type="java.lang.AssertionError" message="Expected HTTP status code 400, but was 200 expected [400] but found [200]">
      <![CDATA[java.lang.AssertionError: Expected HTTP status code 400, but was 200 expected [400] but found [200]
at api.client.ResponseWrapper.expectingStatusCode(ResponseWrapper.java:49)
at api.PlayerUpdateTest.assertUpdatePlayerWithValidationError(PlayerUpdateTest.java:301)
at api.PlayerUpdateTest.testUpdatePlayerWithInvalidGender(PlayerUpdateTest.java:182)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- testUpdatePlayerWithInvalidGender -->
  <testcase classname="api.PlayerUpdateTest" name="testUpdatePlayerScreenName" time="10.179">
    <failure type="java.lang.AssertionError" message="ScreenName should be updated correctly expected [bf7ed155] but found [de2d1a83]">
      <![CDATA[java.lang.AssertionError: ScreenName should be updated correctly expected [bf7ed155] but found [de2d1a83]
at api.PlayerUpdateTest.verifyPlayerFieldUpdate(PlayerUpdateTest.java:289)
at api.PlayerUpdateTest.testUpdatePlayerScreenName(PlayerUpdateTest.java:119)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- testUpdatePlayerScreenName -->
  <testcase classname="api.PlayerUpdateTest" name="testUpdatePlayerWithInvalidPassword" time="0.0">
    <skipped/>
  </testcase> <!-- testUpdatePlayerWithInvalidPassword -->
  <testcase classname="api.PlayerUpdateTest" name="testUpdatePlayerWithAdminEditor" time="10.185"/>
  <testcase classname="api.PlayerUpdateTest" name="testUserCanUpdateOwnProfile" time="0.0">
    <skipped/>
  </testcase> <!-- testUserCanUpdateOwnProfile -->
  <testcase classname="api.PlayerUpdateTest" name="testUpdatePlayerWithNonExistentEditor" time="0.0">
    <skipped/>
  </testcase> <!-- testUpdatePlayerWithNonExistentEditor -->
  <testcase classname="api.PlayerUserEditorNegativeTest" name="testUpdatePlayerWithUserEditor" time="0.085">
    <failure type="java.lang.AssertionError" message="Expected HTTP status code 403, but was 200 expected [403] but found [200]">
      <![CDATA[java.lang.AssertionError: Expected HTTP status code 403, but was 200 expected [403] but found [200]
at api.client.ResponseWrapper.expectingStatusCode(ResponseWrapper.java:49)
at api.PlayerUserEditorNegativeTest.assertUpdatePlayerWithAuthorizationError(PlayerUserEditorNegativeTest.java:107)
at api.PlayerUserEditorNegativeTest.testUpdatePlayerWithUserEditor(PlayerUserEditorNegativeTest.java:72)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- testUpdatePlayerWithUserEditor -->
  <testcase classname="api.PlayerUserEditorNegativeTest" name="testUserCannotDeleteOtherUsers" time="0.091">
    <failure type="java.lang.AssertionError" message="Status code should be 403 when user tries to delete another user expected [403] but found [204]">
      <![CDATA[java.lang.AssertionError: Status code should be 403 when user tries to delete another user expected [403] but found [204]
at api.PlayerUserEditorNegativeTest.testUserCannotDeleteOtherUsers(PlayerUserEditorNegativeTest.java:84)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- testUserCannotDeleteOtherUsers -->
  <testcase classname="base.BaseTest" name="@BeforeSuite globalSetup" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite globalSetup -->
  <testcase classname="base.BaseTest" name="@BeforeSuite globalSetup" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite globalSetup -->
  <testcase classname="base.BaseTest" name="@BeforeSuite globalSetup" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite globalSetup -->
  <testcase classname="base.BaseTest" name="@BeforeSuite globalSetup" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite globalSetup -->
  <testcase classname="base.BaseTest" name="@BeforeSuite globalSetup" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite globalSetup -->
  <testcase classname="base.BaseTest" name="@BeforeSuite globalSetup" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite globalSetup -->
  <testcase classname="base.BaseTest" name="@BeforeSuite globalSetup" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite globalSetup -->
  <testcase classname="base.BaseTest" name="@BeforeSuite globalSetup" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite globalSetup -->
  <testcase classname="base.BaseTest" name="@BeforeSuite globalSetup" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite globalSetup -->
</testsuite> <!-- Player Controller Tests -->
