<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="QIN5CD04618ZL" failures="2" tests="2" name="api.PlayerCreateDuplicateNegativeTest" time="0.870" errors="0" timestamp="2025-08-10T20:08:30 TRT" skipped="0">
  <testcase classname="api.PlayerCreateDuplicateNegativeTest" name="testCreatePlayerWithDuplicateLogin" time="0.423">
    <failure message="Expected HTTP status code 403, but was 200 expected [403] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Expected HTTP status code 403, but was 200 expected [403] but found [200]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at api.client.ResponseWrapper.expectingStatusCode(ResponseWrapper.java:49)
at api.PlayerCreateDuplicateNegativeTest.assertCreatePlayerWithValidationError(PlayerCreateDuplicateNegativeTest.java:92)
at api.PlayerCreateDuplicateNegativeTest.testCreatePlayerWithDuplicateLogin(PlayerCreateDuplicateNegativeTest.java:61)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- testCreatePlayerWithDuplicateLogin -->
  <testcase classname="api.PlayerCreateDuplicateNegativeTest" name="testCreatePlayerWithDuplicateScreenName" time="0.447">
    <failure message="Expected HTTP status code 403, but was 200 expected [403] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Expected HTTP status code 403, but was 200 expected [403] but found [200]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at api.client.ResponseWrapper.expectingStatusCode(ResponseWrapper.java:49)
at api.PlayerCreateDuplicateNegativeTest.assertCreatePlayerWithValidationError(PlayerCreateDuplicateNegativeTest.java:92)
at api.PlayerCreateDuplicateNegativeTest.testCreatePlayerWithDuplicateScreenName(PlayerCreateDuplicateNegativeTest.java:69)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- testCreatePlayerWithDuplicateScreenName -->
</testsuite> <!-- api.PlayerCreateDuplicateNegativeTest -->
